# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GenerateCodeForArrayConstruction <- function(formula) {
    .Call('afCEC_GenerateCodeForArrayConstruction', PACKAGE = 'afCEC', formula)
}

UpdateMeansForQuadraticFunction <- function(res) {
    invisible(.Call('afCEC_UpdateMeansForQuadraticFunction', PACKAGE = 'afCEC', res))
}

GenerateCodeForUpdatingMeans <- function(formula) {
    .Call('afCEC_GenerateCodeForUpdatingMeans', PACKAGE = 'afCEC', formula)
}

CalculateEllipsesOfConfidenceForQuadraticFunction <- function(res, confidence, segments) {
    .Call('afCEC_CalculateEllipsesOfConfidenceForQuadraticFunction', PACKAGE = 'afCEC', res, confidence, segments)
}

GenerateCodeForCalculatingEllipseOfConfidence <- function(formula) {
    .Call('afCEC_GenerateCodeForCalculatingEllipseOfConfidence', PACKAGE = 'afCEC', formula)
}

GenerateCodeForCalculatingEllipsoidsOfConfidence <- function(formula) {
    .Call('afCEC_GenerateCodeForCalculatingEllipsoidsOfConfidence', PACKAGE = 'afCEC', formula)
}

afCECCppRoutine <- function(points, maxClusters, initialLabels, cardMin, minIterations, maxIterations, numberOfStarts, method, values, interactive) {
    .Call('afCEC_afCECCppRoutine', PACKAGE = 'afCEC', points, maxClusters, initialLabels, cardMin, minIterations, maxIterations, numberOfStarts, method, values, interactive)
}

RandIndex <- function(labels1, labels2, maxClusters1, maxClusters2) {
    .Call('afCEC_RandIndex', PACKAGE = 'afCEC', labels1, labels2, maxClusters1, maxClusters2)
}

JaccardIndex <- function(labels1, labels2, maxClusters1, maxClusters2) {
    .Call('afCEC_JaccardIndex', PACKAGE = 'afCEC', labels1, labels2, maxClusters1, maxClusters2)
}

SampleMeshUniform <- function(fName, pointsNum) {
    .Call('afCEC_SampleMeshUniform', PACKAGE = 'afCEC', fName, pointsNum)
}

